services:
  nozomi-s-recipes-front-app:
    build:
      context: .
      args:
        - 'MICROCMS_SERVICE_DOMAIN=${MICROCMS_SERVICE_DOMAIN}'
        - 'MICROCMS_API_KEY=${MICROCMS_API_KEY}'
        - 'NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}'
        - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}'
        - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}' # ビルド時の引数として渡す場合
    ports:
      - '3088:3000'
    environment:
      - 'MICROCMS_SERVICE_DOMAIN=${MICROCMS_SERVICE_DOMAIN}'
      - 'MICROCMS_API_KEY=${MICROCMS_API_KEY}'
      - 'NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}' # ビルド時の引数として渡す場合
